{% set name = "fastmdsimulation" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/aai-research-lab/FastMDSimulation.git
  git_rev: v{{ version }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools
    - wheel
    - numpy
  run:
    - python >=3.10
    - openmm >=8.0
    - openmmforcefields >=0.11.2
    - pdbfixer >=1.9
    - mdtraj >=1.9.9
    - pyyaml >=6.0.1
    - rich >=13.7.0
    - numpy >=1.21

test:
  imports:
    - fastmdsimulation
    - fastmdsimulation.engines
    - fastmdsimulation.core
    - fastmdsimulation.utils
  commands:
    - fastmds --help
    - python -c "import fastmdsimulation; print('Base import successful')"
    - python -c "from fastmdsimulation.engines.openmm_engine import _select_platform; print('OpenMM engine utilities imported')"
  requires:
    - pip

about:
  home: https://github.com/aai-research-lab/FastMDSimulation
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Automated Molecular Dynamics Simulation Setup and Analysis'
  description: |
    FastMDSimulation automates molecular dynamics simulation setup, running, and analysis.
    It supports multiple file formats (PDB, AMBER, GROMACS, CHARMM) and provides
    a streamlined workflow for high-throughput MD simulations.
    
    Note: For full analysis capabilities, install fastmdanalysis separately via pip.
  doc_url: https://github.com/aai-research-lab/FastMDSimulation
  dev_url: https://github.com/aai-research-lab/FastMDSimulation

extra:
  recipe-maintainers:
    - ainaadekunle