
project: WaterBox

defaults:
  engine: openmm
  platform: auto
  temperature_K: 300
  timestep_fs: 2.0
  report_interval: 100
  checkpoint_interval: 500
  ionic_strength_molar: 0.00
  neutralize: false
  box_padding_nm: 0.0
  
stages:
  - { name: minimize,   steps: 0 }
  - { name: nvt,        steps: 5000, ensemble: NVT }
  - { name: npt,        steps: 5000, ensemble: NPT }
  - { name: production, steps: 10000, ensemble: NPT }
  
systems:
  - id: water2nm
    fixed_pdb: water2nm.pdb
    
sweep: { temperature_K: [300] }

